import { IHero } from './hero';

export const heroes: IHero[] = [
  {
    name: 'Guko',
    powers: 'Fly, Kamehameha',
    rating: 2,
    description: 'Strongest One',
    id: '88sgRLn3jSdKOBTqF1tx',
  },
  {
    name: 'Vegita',
    powers: 'Fly, Final Flash',
    rating: 3,
    description: '2nd One in power',
    id: 'r7gme6KkmcWAXCZkGJ2y',
  },
  {
    name: 'Broly',
    powers: 'Ki Blast, Huge Rage',
    rating: 5,
    description: 'Has a huge rage till madness',
    id: 'T9YBUNU55DYaWdJep7T9',
  },
  {
    name: 'Frieza',
    powers: 'Super Cannon Ball, Fly',
    rating: 1,
    description: 'The Big Villan',
    id: 'WZoxa1hLKd31AHr6jxQi',
  },
  {
    name: 'Beerus',
    powers: 'Fly, Destruction',
    rating: 4,
    description: 'Master Of Destruction',
    id: 'raG9ri1TITDwwXltluid',
  },
  {
    name: 'Whis',
    powers: 'Fly, Super Fast',
    rating: 3,
    description: 'Beerus Guard',
    id: 'FLwdFDBuqX6lk12yHUSS',
  },
  {
    name: 'Barry Allen',
    powers: 'Super Fast',
    rating: 4,
    description: 'The fastest man alive',
    id: 'H9aVy4Zm42ZxX9Umtnay',
  },
  {
    name: 'Super Man',
    powers: 'Laser eye, Powerfull',
    rating: 1,
    description: 'The most powerful character in DC Universe',
    id: 'jdmOzhGhbLoygayjbnmK',
  },
  {
    name: 'Iron Man',
    powers: 'Fly, Laser Beam',
    rating: 5,
    description: 'The Savior in End Game',
    id: 'pGOXnoRWYV5Lda7Li03B',
  },
  {
    name: 'Naruto',
    powers: 'Rasengan, Kgebungin no Jitsu',
    rating: 3,
    description: 'Jinshoriki EL Kubi ',
    id: 'EkKtuqWJWLZxuxKlNHnc',
  },
  {
    name: 'Sasuke',
    powers: 'Shidori, Sahrengan',
    rating: 4,
    description: 'The Last Uchiha Shinubi',
    id: 'Pk2xT2gj1vuVmkzCm1JV',
  },
  {
    name: 'Uchiha Madara',
    powers: 'Renegan, Rasengan',
    rating: 5,
    description: 'Villan come with Edu Tense Jitsu (The forbidden one)',
    id: '6lwyRaWTK3PwJqfd5tAk',
  },
  {
    name: 'Sakura',
    powers: 'Healer, Powerful',
    rating: 5,
    description: 'The best Healer in the anime',
    id: 'kExs6PmGjv6IQodHy7wU',
  },
  {
    name: 'Harry Potter',
    powers: 'Expeliarmes, Instant transfer',
    rating: 3,
    description: 'The magician from Grefindoor',
    id: 'kkLrb5yAN06gkCQddjT3',
  },
  {
    name: 'Voldomord',
    powers: 'Avadakadavra',
    rating: 2,
    description: 'The most powerful Villan in the movie',
    id: '7Zm0xoht9fXrIToZicj5',
  },
];
